import type { ProjectConfig, PackageManager } from '../types.js';
import { STALE_SECS } from '../loop/constants.js';

interface HookEntry {
  type: 'command' | 'prompt' | 'agent';
  command?: string;
  prompt?: string;
  model?: string;
  timeout?: number;
  statusMessage?: string;
  async?: boolean;
}

interface HookMatcher {
  matcher?: string;
  hooks: HookEntry[];
}

interface HooksConfig {
  description: string;
  hooks: Record<string, HookMatcher[]>;
}

/**
 * One-liner that removes a stale ownership sentinel (heartbeat older than the
 * 900s threshold) on session start. A crashed loop leaves its sentinel behind,
 * and `/converge --resume` reads that file to decide where to re-enter — so a
 * dead one has to go. Always exits 0 — a best-effort sweep that never blocks the
 * session. Mirrored in templates/marketplace/hooks.json.
 */
const SWEEP_STALE_SENTINEL =
  `if [ -f .claude/.loop-owner ]; then HB=$(grep -o '"heartbeat":[0-9]*' .claude/.loop-owner | grep -o '[0-9]*'); if [ -n "$HB" ] && [ $(( $(date +%s) - HB )) -ge ${STALE_SECS} ]; then rm -f .claude/.loop-owner; fi; fi; exit 0`;

/**
 * Releases the ownership sentinel when the turn dies on an unrecoverable error.
 * The owning turn is gone, so its sentinel is dead regardless of the heartbeat —
 * without this it reads as an in-flight phase for the full staleness window (FR-3).
 *
 * Guarded on `owner:machine`: a human-owned barrier is never cleared by a failed
 * turn, so a human hitting a rate limit at an `owner:human` phase keeps its
 * sentinel and resumes where it left off.
 */
const RELEASE_SENTINEL =
  `if [ -f .claude/.loop-owner ] && grep -q '"owner":"machine"' .claude/.loop-owner; then rm -f .claude/.loop-owner; fi; exit 0`;

/** Error types that kill an autonomous run rather than pausing it. */
const FATAL_STOP_ERRORS = 'rate_limit|overloaded|authentication_failed';

/**
 * Shell `case` patterns the auto-lint script treats as lintable source.
 *
 * The filter lives in the script, not in a hook `if:` condition: the script
 * reads the real `tool_input.file_path` for both `Write` and `Edit`, which a
 * path rule cannot be relied on to do, and one implementation keeps the
 * generated hooks and the bundled `auto-lint.sh` in step.
 */
function lintablePatterns(config: ProjectConfig): string[] {
  const base = ['*.ts', '*.tsx', '*.js', '*.jsx', '*.mjs', '*.cjs'];
  switch (config.framework) {
    case 'vue':
    case 'nuxt':
      return [...base, '*.vue'];
    case 'svelte':
    case 'sveltekit':
      return [...base, '*.svelte'];
    case 'astro':
      return [...base, '*.astro'];
    default:
      return base;
  }
}

/**
 * Generates the `auto-lint.sh` the PostToolUse hook runs.
 *
 * Mirrors `templates/marketplace/auto-lint.sh`, with the project's package
 * manager and lint command baked in. An unreadable payload falls through to
 * linting, preserving the prior behaviour.
 */
export function generateAutoLintScript(
  config: ProjectConfig,
  packageManager: PackageManager
): string {
  const lintFixCmd = buildLintFixCommand(packageManager, config);

  return `#!/bin/bash
# Auto-lint after source file changes
# Generated by devtronic

# Only lint source edits — writing a README must not trigger a full lint pass.
INPUT=$(cat 2>/dev/null)
FILE=$(printf '%s' "$INPUT" | node -e "let d='';process.stdin.on('data',c=>d+=c).on('end',()=>{try{process.stdout.write(JSON.parse(d).tool_input?.file_path||'')}catch(e){}})" 2>/dev/null)
case "$FILE" in
  "") ;; # couldn't determine the file — preserve prior behavior
  ${lintablePatterns(config).join('|')}) ;; # lintable source
  *) exit 0 ;; # non-source edit — nothing to lint
esac

${lintFixCmd} 2>/dev/null || true
`;
}

/**
 * Generates the `version-check.sh` the SessionStart hook runs.
 *
 * Identical to `templates/marketplace/version-check.sh` — the script takes no
 * project configuration, so the two copies are the same text and a test holds
 * them that way. The generated and bundled `hooks.json` drifted apart once
 * already; this is the same guard applied before it can happen again.
 */
export function generateVersionCheckScript(): string {
  return `#!/bin/bash
# Tells you when the project's devtronic files and the installed CLI have
# drifted apart. Generated by devtronic.
#
# Read-only and local: it reads two version strings and prints at most one
# line. It never fetches, never writes, and always exits 0 — a session must
# never fail to start because of this check.
#
# Detection only, on purpose. \`devtronic update\` deletes files the templates
# retired and asks about the ones you made yours, so it needs a human.

MANIFEST=".ai-template/manifest.json"
[ -f "$MANIFEST" ] || exit 0

# The version that last wrote this project's files. It is the first "version"
# key in the manifest; the per-file entries carry checksums, not versions.
PROJECT=$(grep -o '"version"[[:space:]]*:[[:space:]]*"[^"]*"' "$MANIFEST" 2>/dev/null \\
  | head -1 | sed 's/.*"\\([^"]*\\)"$/\\1/')
[ -n "$PROJECT" ] || exit 0

if command -v devtronic >/dev/null 2>&1; then
  CLI=$(devtronic --version 2>/dev/null)
elif command -v npx >/dev/null 2>&1; then
  CLI=$(npx --no-install devtronic --version 2>/dev/null)
fi
[ -n "$CLI" ] || exit 0

[ "$PROJECT" = "$CLI" ] && exit 0

# Which side is behind decides which command fixes it. If \`sort -V\` cannot
# order them, say what we know and let the human choose.
OLDEST=$(printf '%s\\n%s\\n' "$PROJECT" "$CLI" | sort -V 2>/dev/null | head -1)

if [ "$OLDEST" = "$PROJECT" ]; then
  echo "devtronic: this project was last written by $PROJECT, the CLI is $CLI. Run \\\`devtronic update\\\` to bring the project files in step."
elif [ "$OLDEST" = "$CLI" ]; then
  echo "devtronic: the CLI is $CLI but this project was written by $PROJECT. Run \\\`npm i -g devtronic@latest\\\` before updating anything."
else
  echo "devtronic: project $PROJECT, CLI $CLI — the two have drifted."
fi

exit 0
`;
}

/**
 * Generates a hooks.json configuration personalized by the project's
 * package manager and quality command.
 *
 * Hooks included:
 * - SessionStart: quick project orientation (prompt, Haiku 4.5)
 * - PostToolUse(Write|Edit): auto-lint after each file change (command)
 * - SubagentStop: validate subagent output (prompt, Haiku 4.5)
 * - PreCompact: auto-checkpoint before context compaction (command)
 */
export function generateHooks(): string {
  const hooksConfig: HooksConfig = {
    description: 'r-bart devtronic — workflow hooks',
    hooks: {
      SessionStart: [
        {
          matcher: 'startup',
          hooks: [
            {
              type: 'prompt',
              prompt:
                'Quick project orientation: First check if thoughts/STATE.md exists — if so, read it and summarize the current project state. Then check git status, recent commits, and any in-progress work. Give a 3-line summary prioritizing STATE.md context if available.\n\nContext: $ARGUMENTS',
              model: 'claude-haiku-4-5-20251001',
              timeout: 30,
            },
          ],
        },
        {
          // Belt-and-suspenders reclaim: if a loop crashed, sweep its stale
          // ownership sentinel so `/converge --resume` never reads a dead phase
          // as in flight (FR-3 crash lifecycle).
          matcher: 'startup',
          hooks: [
            {
              type: 'command',
              command: SWEEP_STALE_SENTINEL,
              timeout: 10,
            },
          ],
        },
        {
          // Says so when the project's files and the CLI have drifted. Silent
          // when they agree, and it never applies anything: `update` retires
          // files and asks about the ones you made yours, so it needs a human.
          matcher: 'startup',
          hooks: [
            {
              type: 'command',
              command: '${CLAUDE_PLUGIN_ROOT}/scripts/version-check.sh 2>/dev/null || true',
              timeout: 15,
            },
          ],
        },
      ],
      // Synchronous lint-fix: must complete before Claude reads the file again.
      // The script filters non-source edits (see generateAutoLintScript).
      PostToolUse: [
        {
          matcher: 'Write|Edit',
          hooks: [
            {
              type: 'command',
              command: '${CLAUDE_PLUGIN_ROOT}/scripts/auto-lint.sh 2>/dev/null || true',
              timeout: 30,
              statusMessage: 'Auto-linting...',
            },
          ],
        },
      ],
      // A turn that dies on a rate limit leaves a fresh sentinel behind. Release
      // it here so the next turn does not read a dead phase as in flight.
      StopFailure: [
        {
          matcher: FATAL_STOP_ERRORS,
          hooks: [
            {
              type: 'command',
              command: RELEASE_SENTINEL,
              timeout: 10,
            },
          ],
        },
      ],
      SubagentStop: [
        {
          hooks: [
            {
              type: 'prompt',
              prompt: [
                'A subagent has finished. Based on the metadata below, assess if it completed successfully.',
                'Consider the agent type and whether the session ended normally.',
                'Respond with {"ok": true} if it appears complete, or {"ok": false, "reason": "..."} if something seems off.',
                '',
                'IMPORTANT: If stop_hook_active is true, always respond {"ok": true} to prevent infinite loops.',
                '',
                'Context: $ARGUMENTS',
              ].join('\n'),
              model: 'claude-haiku-4-5-20251001',
              timeout: 30,
            },
          ],
        },
      ],
      PreCompact: [
        {
          matcher: 'auto',
          hooks: [
            {
              type: 'command',
              command: '${CLAUDE_PLUGIN_ROOT}/scripts/checkpoint.sh',
              timeout: 30,
              statusMessage: 'Auto-checkpoint before compaction...',
            },
          ],
        },
      ],
    },
  };

  return JSON.stringify(hooksConfig, null, 2);
}

/**
 * Builds the lint-fix shell command for the detected package manager.
 */
function buildLintFixCommand(packageManager: PackageManager, config: ProjectConfig): string {
  const pm = packageManager || 'npm';
  const run = pm === 'npm' ? 'npm run' : pm;

  // If the project has a lint script, use lint:fix variant
  if (config.qualityCommand.includes('lint')) {
    return `${run} lint:fix -- --quiet`;
  }
  return `${run} lint --fix --quiet`;
}

/**
 * Generates the checkpoint.sh script used by the PreCompact hook.
 */
export function generateCheckpointScript(): string {
  return `#!/bin/bash
# Auto-checkpoint before context compaction
# Generated by devtronic

CHECKPOINT_DIR="thoughts/checkpoints"
TIMESTAMP=$(date +%Y%m%d_%H%M%S)

mkdir -p "$CHECKPOINT_DIR"

{
  echo "# Auto-checkpoint: $TIMESTAMP"
  echo ""
  echo "## Git Status"
  git diff --stat 2>/dev/null || echo "Not a git repo"
  echo ""
  echo "## Recent Commits"
  git log --oneline -5 2>/dev/null || echo "No commits"
} > "$CHECKPOINT_DIR/\${TIMESTAMP}_pre-compact.md"

echo "Checkpoint saved: $CHECKPOINT_DIR/\${TIMESTAMP}_pre-compact.md"

# Update persistent state (minimal — skill-level checkpoint writes richer state).
# Never clobber a richer STATE.md written by /checkpoint or a human.
STATE_FILE="thoughts/STATE.md"
mkdir -p "$(dirname "$STATE_FILE")"
if [ -f "$STATE_FILE" ] && ! grep -q "(auto-compact)" "$STATE_FILE"; then
  echo "Preserved existing STATE.md — see the pre-compact checkpoint for context."
else
BRANCH=$(git branch --show-current 2>/dev/null || echo "unknown")
{
  echo "# Project State"
  echo ""
  echo "**Updated**: $(date '+%Y-%m-%d %H:%M') (auto-compact)"
  echo "**Branch**: $BRANCH"
  echo ""
  echo "## Last Auto-Checkpoint"
  echo ""
  echo "Context was compacted. See: \\\`$CHECKPOINT_DIR/\${TIMESTAMP}_pre-compact.md\\\`"
  echo ""
  echo "## Recent Commits"
  echo ""
  git log --oneline -5 2>/dev/null || echo "No commits"
} > "$STATE_FILE"
fi
`;
}
