/**
 * End-to-end for the retirement: run the real `updateCommand()` on a plugin-mode
 * install whose template files are already current.
 *
 * That is the case the first attempt got wrong. The retirement lived inside the
 * plugin-regeneration block, which sits *after* the "All files are up to date!"
 * exit — so the install most likely to be carrying the dead script was the one
 * that never reached the code meant to remove it.
 */
import { describe, it, expect, beforeEach, afterEach, vi } from 'vitest';
import { mkdtempSync, mkdirSync, writeFileSync, rmSync, existsSync, readFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { join } from 'node:path';
import { tmpdir } from 'node:os';

vi.mock('../../utils/tty.js', () => ({ ensureInteractive: () => {} }));

/** Answers keyed on the prompt text — a migration would delete the whole plugin
 *  directory and prove nothing about the retirement. */
vi.mock('@clack/prompts', () => {
  const noop = () => {};
  return {
    intro: noop,
    outro: noop,
    note: noop,
    cancel: noop,
    log: { info: noop, success: noop, warn: noop, error: noop, step: noop, message: noop },
    spinner: () => ({ start: noop, stop: noop, message: noop }),
    isCancel: () => false,
    confirm: async ({ message }: { message: string }) => !message.startsWith('Migrate'),
    select: async () => 'keep',
    multiselect: async () => [],
    text: async () => '',
  };
});

const PLUGIN_PATH = '.claude-plugins/devtronic';
const STOP_GUARD = `${PLUGIN_PATH}/scripts/stop-guard.sh`;
const AUTO_LINT = `${PLUGIN_PATH}/scripts/auto-lint.sh`;
const SCRIPT_BODY = '#!/bin/bash\n# Generated by devtronic\nexit 0\n';

function checksum(content: string): string {
  return createHash('md5').update(content).digest('hex');
}

function entry(content: string) {
  const sum = checksum(content);
  return { checksum: sum, originalChecksum: sum, modified: false };
}

describe('updateCommand retires stop-guard.sh', () => {
  let tempDir: string;
  let exitSpy: ReturnType<typeof vi.spyOn>;

  function readProjectManifest() {
    return JSON.parse(readFileSync(join(tempDir, '.ai-template', 'manifest.json'), 'utf-8'));
  }

  beforeEach(() => {
    tempDir = mkdtempSync(join(tmpdir(), 'update-retire-'));
    mkdirSync(join(tempDir, PLUGIN_PATH, 'scripts'), { recursive: true });
    mkdirSync(join(tempDir, '.ai-template'), { recursive: true });

    writeFileSync(join(tempDir, STOP_GUARD), SCRIPT_BODY);
    writeFileSync(join(tempDir, AUTO_LINT), SCRIPT_BODY);
    writeFileSync(
      join(tempDir, 'package.json'),
      JSON.stringify({ name: 'temp-project', scripts: { lint: 'eslint .' } })
    );
    writeFileSync(
      join(tempDir, '.ai-template', 'manifest.json'),
      JSON.stringify({
        version: '1.5.1',
        implantedAt: '2026-08-20',
        selectedIDEs: ['claude-code'],
        installMode: 'plugin',
        pluginPath: PLUGIN_PATH,
        projectConfig: {
          architecture: 'clean',
          layers: [],
          stateManagement: [],
          dataFetching: [],
          orm: [],
          testing: [],
          ui: [],
          validation: [],
          framework: 'none',
          qualityCommand: 'npm run lint',
        },
        files: {
          [STOP_GUARD]: entry(SCRIPT_BODY),
          [AUTO_LINT]: entry(SCRIPT_BODY),
        },
      })
    );

    // `process.exit(0)` on a declined prompt would kill the worker.
    exitSpy = vi.spyOn(process, 'exit').mockImplementation((() => undefined) as never);
  });

  afterEach(() => {
    exitSpy.mockRestore();
    rmSync(tempDir, { recursive: true, force: true });
  });

  it('deletes the script and drops it from the manifest', async () => {
    const { updateCommand } = await import('../update.js');
    await updateCommand({ path: tempDir });

    expect(existsSync(join(tempDir, STOP_GUARD))).toBe(false);
    expect(readProjectManifest().files[STOP_GUARD]).toBeUndefined();
  });

  it('leaves the scripts that still ship alone', async () => {
    const { updateCommand } = await import('../update.js');
    await updateCommand({ path: tempDir });

    expect(existsSync(join(tempDir, AUTO_LINT))).toBe(true);
    expect(existsSync(join(tempDir, `${PLUGIN_PATH}/scripts/checkpoint.sh`))).toBe(true);
    expect(existsSync(join(tempDir, `${PLUGIN_PATH}/scripts/version-check.sh`))).toBe(true);
  });

  it('regenerates a plugin that never writes stop-guard.sh again', async () => {
    const { updateCommand } = await import('../update.js');
    await updateCommand({ path: tempDir });

    const hooks = JSON.parse(
      readFileSync(join(tempDir, PLUGIN_PATH, 'hooks', 'hooks.json'), 'utf-8')
    );
    expect(Object.keys(hooks.hooks).sort()).toEqual([
      'PostToolUse',
      'PreCompact',
      'SessionStart',
      'StopFailure',
      'SubagentStop',
    ]);
    expect(existsSync(join(tempDir, STOP_GUARD))).toBe(false);
  });

  it('retires it even when every template file is already current', async () => {
    const { updateCommand } = await import('../update.js');

    // First pass brings the project fully up to date...
    await updateCommand({ path: tempDir });

    // ...then plant the dead script again, as a stale install carries it.
    writeFileSync(join(tempDir, STOP_GUARD), SCRIPT_BODY);
    const manifest = readProjectManifest();
    manifest.files[STOP_GUARD] = entry(SCRIPT_BODY);
    writeFileSync(join(tempDir, '.ai-template', 'manifest.json'), JSON.stringify(manifest));

    // The second pass has nothing else to do — it takes the "up to date" exit.
    await updateCommand({ path: tempDir });

    expect(existsSync(join(tempDir, STOP_GUARD))).toBe(false);
    expect(readProjectManifest().files[STOP_GUARD]).toBeUndefined();
  });

  it('does not touch anything in --dry-run', async () => {
    const { updateCommand } = await import('../update.js');
    await updateCommand({ path: tempDir, dryRun: true });

    expect(existsSync(join(tempDir, STOP_GUARD))).toBe(true);
    expect(readProjectManifest().files[STOP_GUARD]).toBeDefined();
  });

  it('is retired by `regenerate --plugin` too', async () => {
    const { regenerateCommand } = await import('../regenerate.js');
    await regenerateCommand(undefined, { path: tempDir, plugin: true });

    expect(existsSync(join(tempDir, STOP_GUARD))).toBe(false);
    expect(readProjectManifest().files[STOP_GUARD]).toBeUndefined();
    expect(existsSync(join(tempDir, AUTO_LINT))).toBe(true);
  });

  it('does not touch anything in --check', async () => {
    const { updateCommand } = await import('../update.js');
    await updateCommand({ path: tempDir, check: true });

    expect(existsSync(join(tempDir, STOP_GUARD))).toBe(true);
    expect(readProjectManifest().files[STOP_GUARD]).toBeDefined();
  });
});
