#!/bin/bash
# Quality gate: runs checks before allowing Claude to stop
# Generated by devtronic

INPUT=$(cat)

# Prevent infinite loops: if already triggered by a stop hook, allow stop
if echo "$INPUT" | grep -q '"stop_hook_active"[[:space:]]*:[[:space:]]*true'; then
  exit 0
fi

# Run quality checks (monorepo-aware)
# Check each package that has a tsconfig.json (run from package dir to use local tsc)
for tsconfig in packages/*/tsconfig.json; do
  if [ -f "$tsconfig" ]; then
    pkg_dir=$(dirname "$tsconfig")
    if ! (cd "$pkg_dir" && npx tsc --noEmit > /dev/null 2>&1); then
      echo "TypeScript checks failed in $pkg_dir. Fix type errors before stopping." >&2
      exit 2
    fi
  fi
done

# Lint check (skip if no eslint config found)
if [ -f ".eslintrc" ] || [ -f ".eslintrc.js" ] || [ -f ".eslintrc.json" ] || [ -f "eslint.config.js" ] || [ -f "eslint.config.mjs" ]; then
  if ! npx eslint . > /dev/null 2>&1; then
    echo "Lint checks failed. Fix lint errors before stopping." >&2
    exit 2
  fi
fi

exit 0
